# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)
#
language:
  - cpp
services:
  - mysql
before_install:
  - sudo apt-get install libpoco-dev doxygen libgtest-dev libgtest0
  - mysql -u root -e 'create database test;'
install: cmake -DPQ_FOUND=FALSE .
script:
  - make
  - sudo make install
  - ./test/test_db
  - ./test/test_db static
