# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)
#
language:
  - cpp
services:
  - mysql
before_install:
  - sudo apt-get install mysql-dev sqlite-dev libpoco-dev
  - mysql -u root -e 'create database test;'
install: LIBPATH="/usr/local/lib" ./configure --prefix=/usr/local --enable-mysql=/usr --enable-sqlite3=/usr
script:
  - make
  - make install
  - /usr/local/bin/test_db
