# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)
#
language:
  - cpp
services:
  - mysql
  - postgres
before_install:
  - sudo apt-get install libpoco-dev
  - mysql -u root -e 'create database test;'
  - psql -c 'create database postgres;' -U postgres
install: cmake -DPQ_FOUND=FALSE .
script:
  - make
  - sudo make install
  - ./test/test_db
