# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)
#
language:
  - cpp
services:
  - mysql
before_install:
  - sudo apt-get install libpoco-dev
  - mysql -u root -e 'create database test;'
install: 
  - cmake -Dtest=ON -DPQ_FOUND=FALSE .
script:
  - make
  - sudo make install
  - ./test/tests
